### ISSUE TITLE
[Feature Change] Enhance feedme/feemenot & role control

### ISSUE THREAD

**Issue by SenorKarlos** [versx/WhMgr#101]
Per our discussion in Discord, now that DM subs are entirely independent of 'city roles':

- Cities should be renamed to Areas or Zones (or something else everyone likes, configurable even?) as many of us use roles for different neighborhoods/subareas of the cities we serve and the feedme/feedmenot functions added to it's own WhMgr-UI section.

- Upon donor role loss, any roles given via the bot should be removed (and stored for easy restoral in DB?) along with the DM sub pausing.

**Comment by versx** [comment]
Fixed in: https://github.com/versx/WhMgr/commit/c1047c6ed22dc69a99644a30f3b85361a606bf66
