### ISSUE TITLE
Ability to add multiple pokeme subscriptions for the same pokemon

### ISSUE THREAD

**Issue by bradders2000** [versx/WhMgr#117]
I'm not sure if this is a feature request or a bug report, but basically, is it possible to make the following work...

note: this is based on a current PR where you don't notify by area and instead do it by location/distance if no city/area is specified.

.pokeme all 100
.pokeme all 100 30 * all

So I would like notifications of all 100iv pokemon within the configured distance of my location and I would like notifications of all 100iv / level 30+ pokemon within all configured cities/areas.
When testing, it seems the 2nd command overwrites the entries in the pokemon db table that were created by the first one.

**Comment by Dewpg** [comment]
If this happens, please allow for distance unique to each subscription. This would be a huge QOL update.

**Comment by versx** [comment]
Fixed in: https://github.com/versx/WhMgr/pull/158
