### ISSUE TITLE
[Feature Request] - add iv stats post option

### ISSUE THREAD

**Issue by hunch-13** [versx/WhMgr#118]
Similar to Chucks bot, a toggle that could post nightly stats of all the hundos "yesterday" in a simple format.  Useful as incentive to non donors

**Comment by versx** [comment]
Would this be just any Pokemon scanned for IV or only 100s, etc?

**Comment by versx** [comment]
> Would this be just any Pokemon scanned for IV or only 100s, etc?

@hunch-13 Any Pokemon scanned for IV or only 100s?

**Comment by corbindk** [comment]
Not hunch-13, but chucks stat bot did hundos only. like a shiny stats list but 100s scanned instead

**Comment by versx** [comment]
> Not hunch-13, but chucks stat bot did hundos only. like a shiny stats list but 100s scanned instead

Thanks, since we don't currently have a `pokemon_hundo_stats` table, that'll need changing to reference the `pokemon` table.

**Comment by hunch-13** [comment]
basically what corbindk says.  Chucks had a hudno bot (I still use)  that posts nightly stats of hundos from yesterday (runs at 23:59pm and shows from 00:00 to 23:59).  I mean I'm fine to keep using his but I think the gamemaster needs to be updated manually, since whmgr does shiny this could fit in.  No biggie if it doesn't make sense

example screenshot
![image](https://user-images.githubusercontent.com/3146205/124927398-9d480f80-dfcc-11eb-8363-fb43aea1df77.png)

**Comment by versx** [comment]
Added in v5.0.2
