### ISSUE TITLE
Incorrect 'Weakness' listings for Raid Boss Notifications

### ISSUE THREAD

**Issue by kbtbc** [versx/WhMgr#12]
Raid Boss Notifications are getting over-populated with Weakness typing.   This issue seems consistent across all Pokemon Raid Boss types.

Example: 
![image](https://user-images.githubusercontent.com/7109934/82856414-e7128b00-9edb-11ea-8115-57483402eaba.png)
(Bastiodon is only weak to Fighting, Ground & Water)

**Comment by versx** [comment]
Currently, weakness is just included based off general Pokemon type, we would need to change to check against each Pokemon's typing against a dictionary of weaknesses for all Pokemon I believe to correct this.
https://github.com/versx/WhMgr/blob/v3/src/Extensions/PokemonExtensions.cs#L1168

**Comment by kbtbc** [comment]
I think the error is broader than just the general typing.   Take another example:
![image](https://user-images.githubusercontent.com/7109934/82910669-ecea8980-9f38-11ea-9754-e30881583523.png)
Cranidos is only a Rock type Pokemon.  Both the general Rock type, and Cranidos are _only_ weak to:  Fighting, Grass, Ground, Steel, & Water 

Looking more at the weaknesses selected by Whmgr, it appears that is selecting both the correct weaknesses, AND then adding all the weakness types of those selected weakness, too.

**Comment by versx** [comment]
Thanks for the update I'll try getting that fixed today.

**Comment by versx** [comment]
This should be fixed in the `netcore` branch now.

**Comment by versx** [comment]
This should be fixed in latest, if it's not please reopen the issue.
