### ISSUE TITLE
Update PvP subscriptions for level 51

### ISSUE THREAD

**Issue by XerockXMG** [versx/WhMgr#123]
As the title states, PvP subscription calculations need to be updated to go up to level 51 now.

**Comment by versx** [comment]
I honestly can't find anything that would prevent pvp subscriptions with level 51 Pokemon unless the backend wasn't sending it. I only see level 50 notifications myself, can't find any level 51.

![image](https://user-images.githubusercontent.com/1327440/110226075-88356580-7ea0-11eb-8e4e-71db4405ad2f.png)

**Comment by nileplumb** [comment]
was going to suggest this, I assume it's backend related and whmgr isn't doing any rank calculations/referencing

**Comment by versx** [comment]
Closing since not related to WhMgr, but backend that actually sends the PvP rank data.
