### ISSUE TITLE
Support for subbing to Mons by Weight

### ISSUE THREAD

**Issue by dergelm** [versx/WhMgr#131]
Feature request for whmgr/ whmgr-ui
Allow users to sub to Mons by weight. So they can get their big karps with weight over 13.13kg

**Comment by versx** [comment]
@dergelm Would this be based on the referenced enum for Pokemon size? i.e. the user would subscribe to `Tiny` `Small` `Normal` `Large` `Big` `All`/`*` for size or a specific kg?

**Comment by versx** [comment]
Fixed in https://github.com/versx/WhMgr/pull/145
