### ISSUE TITLE
Time zone Quest purging not functioning

### ISSUE THREAD

**Issue by Anonymous899** [versx/WhMgr#146]
Quest purging does not work for different time zones they seem to be clearing during my local time zone rather then area(s) time zone. Config option to adjust time zone should fix it.

**Comment by versx** [comment]
Right, because there's no config option for clearing quests by timezone, it's based on the local machine running it.
I suppose I could break config changes and add a timezone option to the quest channels listed, or it a dictionary by timezone and the keys are the quest channels to purge. 🤔

**Comment by versx** [comment]
Should be fixed in v5.0.2
