### ISSUE TITLE
[Feature] Add Health Endpoint

### ISSUE THREAD

**Issue by thunder123456** [versx/WhMgr#147]
Add health endpoint for monitoring

**Comment by versx** [comment]
Same options as CDC? Which checks the following:
- Discord.com
- MySQL host
- Executing process status
- Hard Drive stats (make sure we aren't filling up disks)
- Max used memory

**Comment by thunder123456** [comment]
Yes the same as CDC and if you can add a avg/max queue time monitor that may help identify if the server needs more resources.
