### ISSUE TITLE
Geofence/Distance - one geofence within another is excluded

### ISSUE THREAD

**Issue by ZombieCorn80** [versx/WhMgr#148]
I have a small geofence 1 (higher priority) from which I report quests.
this is within a larger geofence 2 (lower priority) for which I have set Pokemon reports.
only quests from geofence 1 are reported to me, which is correct.
However, I get Pokemon messages from geofence 2 but not from geofence 1!

the same goes for a geofence and a distance.
I had set all :100: for geofence 2 and icognito with a distance of 15km.
Then only messages outside of geofence 2 came because the 15km overwritten everything but geofence 2 was „cut out“!

looks like one geofence within another is excluded if both are used for reporting. just like a geofence within a radius!

**Comment by SenorKarlos** [comment]
I didn't use priorities when I tried geojson (100+ extra keys didn't sound like fun) but sounds like I'm glad I didn't. Using ini's generated by the converter and they do as they're told and work with distances.

KILL THE PRIORITIES! 😂

**Comment by versx** [comment]
Should be fixed in v5.0.2

**Comment by versx** [comment]
Closing until someone says otherwise.
