### ISSUE TITLE
Great League and Ultra League subscriptions do not work together

### ISSUE THREAD

**Issue by SenorKarlos** [versx/WhMgr#149]
As discussed and evidenced in Discord, a single user (I'd assume a channel as well) cannot subscribe to both GL & UL and receive both notices. Only Great league will come through. Ultra or Great work fine individually.

**Comment by versx** [comment]
Should be fixed in https://github.com/versx/WhMgr/pull/158

**Comment by versx** [comment]
Closing this, if it still persists for some reason, feel free to reopen.
