### ISSUE TITLE
Whmgr database version

### ISSUE THREAD

**Issue by clburlison** [versx/WhMgr#170]
Please consider a `metadata` table and moving the `db_version` from `./bin/static/app/db_verison.txt` into a database field. This makes testing much easier. Additionally restoring from backups can be done more confidently.

**Comment by versx** [comment]
I'll change it back, was originally using a `metadata` table for `DB_VERSION`, but changed it to try and help circumvent the 10 table limit I was originally limited to with the ServiceStack.OrmLite library. Since I provided a license this shouldn't be an issue anymore. (I hope lol)

**Comment by versx** [comment]
Fixed in v5.0.2
