### ISSUE TITLE
Inconsistent PvP DMs

### ISSUE THREAD

**Issue by habalushy** [versx/WhMgr#182]
During the Ultra Unlock event, several people reported that Shieldon PvP DMs were not working. The rdm is sending the correct rank, notifications were showing up in channel feeds; however, DMs were not being sent. I noticed this issue for some other species too (e.g., pidgey), while some still seemed to work (e.g., duskull). 
(I also wasn't getting 100% shieldon DMs either, not sure if that's related...)

**Comment by versx** [comment]
Should be fixed in v5.0.2
