### ISSUE TITLE
Non-IV mons no longer get reported by DM

### ISSUE THREAD

**Issue by SenorKarlos** [versx/WhMgr#185]
Per user report and confirmed myself, Subscriptions being created with nothing but the mon specified are only returning IV'd results. Testing with  Pikachu, I watched 2 separate mons appear in a zone with only 'Nearby Pokestop' scanning but got no alert, then watched one get picked up on a nearby and IV'd, and only got the IV alert. Have not tested if it affects channels, this is by DM.

**Comment by versx** [comment]
Should be fixed in v5.0.2
