### ISSUE TITLE
v5 not syncing updates from UI

### ISSUE THREAD

**Issue by clburlison** [versx/WhMgr#192]
Not sure how to troubleshoot or provide logs for this one however using the latest commits of WhMgr v5 rewrite branch and the UI rewrite branch it seems that it is not pulling database updates for subscriptions. Tried this by 
1. starting the service `dotnet Whmgr.dll`
2. Adding a pokemon subscription via UI
3. waiting up to 10 minutes with no DMs
4. stop and restart Whmgr
5. Within a few seconds of start DMs start coming through

**Comment by versx** [comment]
This should be fixed in latest push now.

**Comment by clburlison** [comment]
Confirmed this has fixed
