### ISSUE TITLE
List all subscriptions with .info command

### ISSUE THREAD

**Issue by versx** [versx/WhMgr#53]
List complete subscriptions list for Pokemon

**Comment by Dewpg** [comment]
This is closed already, right?

**Comment by versx** [comment]
> This is closed already, right?

No, Pokemon subscriptions are grouped based on most common IV when they are listed from the `.info` command. My issue is basically saying to remove the grouped list (maybe if there are differences i.e. all are 100s but a couple are 100s are level 30 or something that differentiates from the most common, otherwise maybe keep the group) instead of always grouping them regardless.

**Comment by versx** [comment]
No longer valid
