### ISSUE TITLE
[Feature] Raid Egg subscriptions

### ISSUE THREAD

**Issue by rexbutz** [versx/WhMgr#80]
Allow for subscriptions for raid eggs.

**Comment by versx** [comment]
Should this be a separate command or tied into the `raidme` and `raidmenot` commands? If the latter, how?

**Comment by Dewpg** [comment]
If you sub to something that is in a 5* egg, then get notified of 5*s.  If you sub to a 1* raidboss, get notified of 1* eggs. No additional commands, just derive the egg pool they want from their raid subs?

**Comment by Dewpg** [comment]
Or just .raidme 1*....  .raidme 5*,6*.

**Comment by rexbutz** [comment]
I think it would make sense to make it separate with an .eggme 1 (or .eggmenot), unless it's easier to make the eggs "pokemon" with the .raidme/.raidmenot (IE .raidme level3 [like .raidme azelf]).   I haven't looked at the code to see how the ".raidme azelf" is triggered, so can't honestly say which makes more sense.

**Comment by versx** [comment]
> If you sub to something that is in a 5* egg, then get notified of 5_s. If you sub to a 1_ raidboss, get notified of 1* eggs. No additional commands, just derive the egg pool they want from their raid subs?

I think I'll just go with this to be honest, then add an option in the UI whether to send the egg notification of the raid subscription or not.

**Comment by versx** [comment]
Fixed in https://github.com/versx/WhMgr/pull/150
