### ISSUE TITLE
Discord rate limit is hit on startup when multiple "get guild member" calls are made simultaneously

### ISSUE THREAD

**Issue by ArcanoxDragon** [versx/WhMgr#93]
If webhooks come in right after the bot is started, it starts trying to request member info from multiple threads at once while Emojis are still being loaded, causing this:
![image](https://user-images.githubusercontent.com/816612/101297950-2dcd3000-37f1-11eb-85d9-ddd08b8ba917.png)

I have a fix for this already which batches simultaneous requests to the same guild/user combination if there is no cache in place for that user.

**Comment by ArcanoxDragon** [comment]
Closed by #94 (GitHub didn't recognize my "addresses" wording in the PR apparently 😉)

**Comment by versx** [comment]
> Closed by #94 (GitHub didn't recognize my "addresses" wording in the PR apparently 😉)

I learned that too, that it doesn't recognize `addresses` as the closing/tagging keyword a while back lol. You'd think it would.
